const posixRegexp = /^[0-7][0-7][0-7][0-7]?$/;

export default [{
  name: 'archiveStorage',
  type: 'checkbox',
  defaultValue: false,
  tip: true,
}, {
  name: 'hostname',
  type: 'text',
  example: 'https://s3.amazonaws.com',
  regex: /^https?:\/\/.*/,
  regexMessage: 'This field should be an URL with http or https scheme',
}, {
  name: 'bucketName',
  type: 'text',
}, {
  name: 'verifyServerCertificate',
  type: 'checkbox',
  defaultValue: true,
  tip: true,
}, {
  name: 'region',
  type: 'text',
  optional: true,
  tip: true,
  defaultPlaceholder: 'us-east-1',
  isDefault: true,
}, {
  name: 'accessKey',
  type: 'text',
  optional: true,
}, {
  name: 'secretKey',
  type: 'password',
  optional: true,
}, {
  name: 'blockSize',
  type: 'number',
  optional: true,
  tip: true,
  notEditable: true,
  defaultPlaceholder: 10485760,
  isDefault: true,
}, {
  name: 'maximumCanonicalObjectSize',
  type: 'number',
  optional: true,
  tip: true,
  gte: 0,
  defaultPlaceholder: 67108864,
  isDefault: true,
}, {
  name: 'fileMode',
  tip: true,
  type: 'text',
  regex: posixRegexp,
  regexMessage: 'This field should be octal POSIX permissions',
  optional: true,
  regexAllowBlank: true,
  defaultPlaceholder: '0664',
  isDefault: true,
}, {
  name: 'dirMode',
  tip: true,
  type: 'text',
  regex: posixRegexp,
  regexMessage: 'This field should be octal POSIX permissions',
  optional: true,
  regexAllowBlank: true,
  defaultPlaceholder: '0775',
  isDefault: true,
}, {
  name: 'timeout',
  type: 'number',
  optional: true,
  defaultPlaceholder: 300000,
  isDefault: true,
}];
