export default [{
  name: 'username',
  type: 'text',
  tip: true,
}, {
  name: 'password',
  type: 'password',
  tip: true,
}, {
  name: 'projectName',
  type: 'text',
  tip: true,
}, {
  name: 'userDomainName',
  type: 'text',
  optional: true,
  defaultPlaceholder: 'Default',
  isDefault: true,
  tip: true,
}, {
  name: 'projectDomainName',
  type: 'text',
  optional: true,
  defaultPlaceholder: 'Default',
  isDefault: true,
  tip: true,
}, {
  name: 'authUrl',
  type: 'text',
  tip: true,
  example: 'http://example.com:5000/v3',
}, {
  name: 'containerName',
  type: 'text',
  tip: true,
}, {
  name: 'blockSize',
  type: 'number',
  optional: true,
  notEditable: true,
  defaultPlaceholder: 10485760,
  isDefault: true,
}, {
  name: 'timeout',
  type: 'number',
  optional: true,
}];
