export default [{
    name: 'endpoint',
    type: 'text',
    tip: true,
    regex: /^https?:\/\/.*/,
    regexMessage: 'This field should be an URL with http or https scheme',
    example: 'https://192.168.1.2:8080/webdav',
  },
  {
    name: 'verifyServerCertificate',
    type: 'checkbox',
    defaultValue: true,
    tip: true,
  },
  {
    name: 'credentialsType',
    type: 'radio-group',
    defaultValue: 'none',
    options: [
      { value: 'none', label: 'none' },
      { value: 'basic', label: 'basic' },
      { value: 'token', label: 'token' },
    ],
    tip: true,
  },
  {
    name: 'credentials',
    type: 'text',
    tip: true,
    optional: true,
    example: 'username:password (for basic credentials type)',
  },
  {
    name: 'authorizationHeader',
    type: 'text',
    tip: true,
    optional: true,
    example: 'Authorization: Bearer <token>',
  },
  {
    name: 'rangeWriteSupport',
    type: 'radio-group',
    defaultValue: 'none',
    options: [
      { value: 'none', label: 'none' },
      { value: 'sabredav', label: 'SabreDAV' },
      { value: 'moddav', label: 'ModDAV' },
    ],
    tip: true,
  },
  {
    name: 'connectionPoolSize',
    type: 'number',
    optional: true,
    gte: 0,
    tip: true,
    example: 25,
  },
  {
    name: 'maximumUploadSize',
    type: 'number',
    optional: true,
    gte: 0,
    tip: true,
    example: 1048576,
  }, {
    name: 'timeout',
    type: 'number',
    optional: true,
  }, {
    name: 'insecure',
    type: 'checkbox',
    defaultValue: false,
    tip: true,
  }, {
    name: 'readonly',
    type: 'checkbox',
    defaultValue: false,
    tip: true,
  },
  // FIXME: check storage path type radio
];
